version: "3.1"

services:
  pg:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: dev-password
      POSTGRES_USER: dev-user
    ports:
      - 6000:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
